### PR TITLE
Fix home page freezing when connecting account

### LINKED ISSUE #8: Site crashes if you connect your wallet on the home page
This is 100% reproducible but only happens if you connect on the homepage, not any other page.

As soon as you connect on another page, you can freely navigate to the homepage without issues.

### PR DESCRIPTION
**Pull request by onbjerg**
Fixes #8

### CODE REVIEW

File: src/views/Home/components/Balances.tsx [hunk 1]
```diff
@@ -68,10 +68,10 @@ const Balances: React.FC = () => {
       const supply = await getSushiSupply(honey)
       setTotalSupply(supply)
     }
-    if (honey) {
+    if (honey && account && getSushiAddress(honey)) {
```
Comment (fabriziovigevani) [inline src/views/Home/components/Balances.tsx]: `getSushiAddress` Already checks if honey is nullable 
```suggestion
    if (account && getSushiAddress(honey)) {
```

File: src/hooks/useTokenBalance.ts [hunk 2]
```diff
@@ -16,15 +16,19 @@ const useTokenBalance = (tokenAddress: string) => {
...
 
   const fetchBalance = useCallback(async () => {
+    if (!tokenAddress) {
+      return
+    }
+
     const balance = await getBalance(ethereum, tokenAddress, account)
     setBalance(new BigNumber(balance))
-  }, [account, ethereum, tokenAddress])
+  }, [account, ethereum, tokenAddress, setBalance])
```
Comment (fabriziovigevani) [inline src/hooks/useTokenBalance.ts]: We can remove `setBalance` as it never changes.
```suggestion
  }, [account, ethereum, tokenAddress])
```

File: src/views/Home/components/Balances.tsx [hunk 3]
```diff
@@ -68,10 +68,10 @@ const Balances: React.FC = () => {
...
       fetchTotalSupply()
     }
-  }, [honey, setTotalSupply])
+  }, [honey, setTotalSupply, account])
```
Comment (fabriziovigevani) [inline src/views/Home/components/Balances.tsx]: Saem here 
```suggestion
  }, [honey, account])
```

**Review by fabriziovigevani — COMMENTED** [review]
The freezing issue is still happening for me.

The problem seems to be in `useAllEarnings` hook where the useEffect runs in a loop.

This is due to `farms` being a dependency of `fetchAllBalances ` which is a dependency of the `useEffect`, and farms is a new array on every re-render.

We can solve this by memoizing the farms value

```
const farms = useMemo(() => getFarms(sushi), [sushi])
```

Though not quite sure yet why the issue doesn't happen when coming from the farms page.

**Review by fabriziovigevani — APPROVED** [review]
Awesome, LGTM!
